using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Randall.Contracts;

namespace Randall.Infrastructure.BugHunt;

/// <summary>
/// Bug Hunter: heuristic AI-vs-human source attribution. Not ground truth —
/// combines annotations, tool markers, and light style signals so campaigns
/// can prioritize AI-attributed regions. Does not judge runtime behavior.
/// </summary>
public static partial class BugHunterAttribution
{
    private static readonly JsonSerializerOptions JsonOpts = new() { WriteIndented = true };

    private static readonly (string Signal, Regex Rx)[] AiMarkers =
    [
        ("annotation:AI-GENERATED", AnnotationAiRegex()),
        ("annotation:BEGIN AI", BeginAiRegex()),
        ("tool:copilot", CopilotRegex()),
        ("tool:chatgpt", ChatGptRegex()),
        ("tool:claude", ClaudeRegex()),
        ("tool:cursor", CursorAgentRegex()),
        ("tool:codegen", CodegenRegex()),
        ("comment:generated by", GeneratedByRegex()),
    ];

    private static readonly (string Signal, Regex Rx)[] HumanMarkers =
    [
        ("annotation:HUMAN", AnnotationHumanRegex()),
        ("annotation:BEGIN HUMAN", BeginHumanRegex()),
    ];

    public static BugHunterScanDto Scan(
        string root,
        IEnumerable<string>? extensions = null,
        int maxFiles = 2000)
    {
        root = Path.GetFullPath(root);
        if (!Directory.Exists(root))
            throw new DirectoryNotFoundException($"Source root not found: {root}");

        var exts = new HashSet<string>(
            (extensions ?? new BugHunterConfig().Extensions)
            .Select(e => e.StartsWith('.') ? e.ToLowerInvariant() : "." + e.ToLowerInvariant()),
            StringComparer.OrdinalIgnoreCase);

        var blocks = new List<BugHunterBlockDto>();
        var files = 0;

        foreach (var file in EnumerateSourceFiles(root, exts))
        {
            if (files >= maxFiles)
                break;
            files++;
            try
            {
                blocks.AddRange(ScanFile(root, file));
            }
            catch
            {
                /* skip unreadable */
            }
        }

        // Collapse: if a file has no block markers, attribute whole file from aggregate signals.
        var ai = blocks.Count(b => b.Provenance is BugHunterProvenance.LikelyAi or BugHunterProvenance.AnnotatedAi);
        var human = blocks.Count(b => b.Provenance is BugHunterProvenance.LikelyHuman or BugHunterProvenance.AnnotatedHuman);
        var unknown = blocks.Count - ai - human;

        var focus = SuggestOracleFocus(blocks);
        var mistakes = SuggestMistakes(blocks);

        return new BugHunterScanDto(
            root, files, ai, human, unknown, blocks, focus, mistakes, DateTimeOffset.UtcNow);
    }

    public static string PersistReport(BugHunterScanDto scan, string outDir)
    {
        Directory.CreateDirectory(outDir);
        var path = Path.Combine(outDir, $"ai_code_{DateTime.UtcNow:yyyyMMdd_HHmmss}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(scan, JsonOpts));
        var md = Path.Combine(outDir, Path.GetFileNameWithoutExtension(path) + ".md");
        File.WriteAllText(md, ToMarkdown(scan));
        return path;
    }

    public static string ToMarkdown(BugHunterScanDto scan)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# AI code attribution report");
        sb.AppendLine();
        sb.AppendLine($"> Heuristic — not ground truth. Generated {scan.At:u}");
        sb.AppendLine();
        sb.AppendLine($"Root: `{scan.Root}`");
        sb.AppendLine($"Files scanned: **{scan.FilesScanned}**");
        sb.AppendLine($"Blocks: AI **{scan.AiBlocks}** · Human **{scan.HumanBlocks}** · Unknown **{scan.UnknownBlocks}**");
        sb.AppendLine();
        sb.AppendLine("## Suggested oracle focus");
        foreach (var s in scan.SuggestedOracleFocus)
            sb.AppendLine($"- `{s}`");
        sb.AppendLine();
        sb.AppendLine("## Suggested AI-mistake classes");
        foreach (var s in scan.SuggestedMistakeClasses)
            sb.AppendLine($"- `{s}`");
        sb.AppendLine();
        sb.AppendLine("## Blocks");
        sb.AppendLine();
        sb.AppendLine("| Provenance | File | Lines | Confidence | Signals |");
        sb.AppendLine("|------------|------|-------|------------|---------|");
        foreach (var b in scan.Blocks
                     .OrderByDescending(b => b.Provenance is BugHunterProvenance.AnnotatedAi or BugHunterProvenance.LikelyAi)
                     .ThenBy(b => b.Path)
                     .ThenBy(b => b.StartLine)
                     .Take(200))
        {
            sb.AppendLine(
                $"| {b.Provenance} | `{b.Path}` | {b.StartLine}–{b.EndLine} | {b.Confidence:0.00} | {string.Join(", ", b.Signals.Take(4))} |");
        }

        if (scan.Blocks.Count > 200)
        {
            sb.AppendLine();
            sb.AppendLine($"… {scan.Blocks.Count - 200} more in JSON report");
        }

        sb.AppendLine();
        sb.AppendLine("## AI-attributed previews");
        foreach (var b in scan.Blocks
                     .Where(b => b.Provenance is BugHunterProvenance.LikelyAi or BugHunterProvenance.AnnotatedAi)
                     .Take(40))
        {
            sb.AppendLine();
            sb.AppendLine($"### `{b.Path}` L{b.StartLine}–{b.EndLine}");
            sb.AppendLine();
            sb.AppendLine("```" + b.Language);
            sb.AppendLine(b.Preview);
            sb.AppendLine("```");
        }

        return sb.ToString();
    }

    private static IEnumerable<string> EnumerateSourceFiles(string root, HashSet<string> exts)
    {
        var skipDirs = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".git", "node_modules", "bin", "obj", ".vs", "dist", "build", "target", "vendor", "__pycache__",
        };

        var stack = new Stack<string>();
        stack.Push(root);
        while (stack.Count > 0)
        {
            var dir = stack.Pop();
            IEnumerable<string> subs;
            try { subs = Directory.EnumerateDirectories(dir); }
            catch { continue; }
            foreach (var sub in subs)
            {
                var name = Path.GetFileName(sub);
                if (skipDirs.Contains(name))
                    continue;
                stack.Push(sub);
            }

            IEnumerable<string> files;
            try { files = Directory.EnumerateFiles(dir); }
            catch { continue; }
            foreach (var file in files)
            {
                if (exts.Contains(Path.GetExtension(file)))
                    yield return file;
            }
        }
    }

    private static IEnumerable<BugHunterBlockDto> ScanFile(string root, string file)
    {
        var rel = Path.GetRelativePath(root, file).Replace('\\', '/');
        var lang = Path.GetExtension(file).TrimStart('.').ToLowerInvariant();
        string[] lines;
        try { lines = File.ReadAllLines(file); }
        catch { yield break; }
        if (lines.Length == 0)
            yield break;

        // 1) Explicit region markers: BEGIN AI … END AI / BEGIN HUMAN … END HUMAN
        var regionBlocks = ExtractMarkedRegions(rel, lang, lines).ToList();
        if (regionBlocks.Count > 0)
        {
            foreach (var b in regionBlocks)
                yield return b;
            yield break;
        }

        // 2) Line-level tool/annotation hits → cluster into blocks
        var hitLines = new List<(int Line, string Signal, bool Ai)>();
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            foreach (var (signal, rx) in HumanMarkers)
            {
                if (rx.IsMatch(line))
                    hitLines.Add((i + 1, signal, false));
            }
            foreach (var (signal, rx) in AiMarkers)
            {
                if (rx.IsMatch(line))
                    hitLines.Add((i + 1, signal, true));
            }
        }

        if (hitLines.Count > 0)
        {
            foreach (var cluster in ClusterHits(hitLines, lines.Length))
            {
                var signals = cluster.Hits.Select(h => h.Signal).Distinct().ToList();
                var aiVotes = cluster.Hits.Count(h => h.Ai);
                var humanVotes = cluster.Hits.Count - aiVotes;
                var provenance = aiVotes >= humanVotes
                    ? (signals.Any(s => s.StartsWith("annotation:", StringComparison.Ordinal))
                        ? BugHunterProvenance.AnnotatedAi
                        : BugHunterProvenance.LikelyAi)
                    : (signals.Any(s => s.StartsWith("annotation:", StringComparison.Ordinal))
                        ? BugHunterProvenance.AnnotatedHuman
                        : BugHunterProvenance.LikelyHuman);
                var conf = Math.Clamp(0.55 + 0.1 * cluster.Hits.Count, 0.55, 0.95);
                yield return new BugHunterBlockDto(
                    rel, cluster.Start, cluster.End, lang, provenance, conf, signals,
                    Preview(lines, cluster.Start, cluster.End));
            }
            yield break;
        }

        // 3) Whole-file style heuristic (weak)
        var style = ScoreStyle(lines);
        if (style.Score >= 0.65)
        {
            yield return new BugHunterBlockDto(
                rel, 1, lines.Length, lang, BugHunterProvenance.LikelyAi, style.Score, style.Signals,
                Preview(lines, 1, Math.Min(lines.Length, 40)));
        }
        else if (style.Score <= 0.35)
        {
            yield return new BugHunterBlockDto(
                rel, 1, lines.Length, lang, BugHunterProvenance.LikelyHuman, 1.0 - style.Score, style.Signals,
                Preview(lines, 1, Math.Min(lines.Length, 40)));
        }
        else
        {
            yield return new BugHunterBlockDto(
                rel, 1, lines.Length, lang, BugHunterProvenance.Unknown, 0.5, style.Signals,
                Preview(lines, 1, Math.Min(lines.Length, 40)));
        }
    }

    private static IEnumerable<BugHunterBlockDto> ExtractMarkedRegions(string rel, string lang, string[] lines)
    {
        int? aiStart = null;
        int? humanStart = null;
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            if (BeginAiRegex().IsMatch(line) ||
                (AnnotationAiRegex().IsMatch(line) && line.Contains("BEGIN", StringComparison.OrdinalIgnoreCase)))
            {
                aiStart = i + 1;
                humanStart = null;
            }
            else if (EndAiRegex().IsMatch(line) && aiStart is int a0)
            {
                yield return new BugHunterBlockDto(
                    rel, a0, i + 1, lang, BugHunterProvenance.AnnotatedAi, 0.98,
                    ["annotation:region-AI"], Preview(lines, a0, i + 1));
                aiStart = null;
            }
            else if (BeginHumanRegex().IsMatch(line))
            {
                humanStart = i + 1;
                aiStart = null;
            }
            else if (EndHumanRegex().IsMatch(line) && humanStart is int h0)
            {
                yield return new BugHunterBlockDto(
                    rel, h0, i + 1, lang, BugHunterProvenance.AnnotatedHuman, 0.98,
                    ["annotation:region-HUMAN"], Preview(lines, h0, i + 1));
                humanStart = null;
            }
        }
    }

    private sealed record HitCluster(int Start, int End, List<(int Line, string Signal, bool Ai)> Hits);

    private static IEnumerable<HitCluster> ClusterHits(
        List<(int Line, string Signal, bool Ai)> hits,
        int lineCount)
    {
        hits.Sort((a, b) => a.Line.CompareTo(b.Line));
        var cluster = new List<(int Line, string Signal, bool Ai)> { hits[0] };
        for (var i = 1; i < hits.Count; i++)
        {
            if (hits[i].Line - cluster[^1].Line <= 40)
            {
                cluster.Add(hits[i]);
            }
            else
            {
                yield return ToCluster(cluster, lineCount);
                cluster = [hits[i]];
            }
        }
        if (cluster.Count > 0)
            yield return ToCluster(cluster, lineCount);
    }

    private static HitCluster ToCluster(List<(int Line, string Signal, bool Ai)> hits, int lineCount)
    {
        var start = Math.Max(1, hits[0].Line - 5);
        var end = Math.Min(lineCount, hits[^1].Line + 25);
        return new HitCluster(start, end, hits);
    }

    private static (double Score, List<string> Signals) ScoreStyle(string[] lines)
    {
        // Weak heuristic: AI-ish = dense explanatory comments, few TODOs, long uniform functions.
        var signals = new List<string>();
        var comment = 0;
        var todo = 0;
        var empty = 0;
        var total = Math.Max(1, lines.Length);
        foreach (var line in lines)
        {
            var t = line.Trim();
            if (t.Length == 0) { empty++; continue; }
            if (t.StartsWith("//") || t.StartsWith('#') || t.StartsWith('*') || t.StartsWith("/*"))
                comment++;
            if (t.Contains("TODO", StringComparison.OrdinalIgnoreCase) ||
                t.Contains("FIXME", StringComparison.OrdinalIgnoreCase) ||
                t.Contains("HACK", StringComparison.OrdinalIgnoreCase))
                todo++;
        }

        var commentRatio = (double)comment / total;
        var todoRatio = (double)todo / total;
        var emptyRatio = (double)empty / total;
        var score = 0.5;
        if (commentRatio > 0.22) { score += 0.12; signals.Add("style:high-comment-ratio"); }
        if (todoRatio < 0.005 && total > 80) { score += 0.08; signals.Add("style:low-todo"); }
        if (emptyRatio < 0.08 && total > 80) { score += 0.05; signals.Add("style:dense"); }
        if (todoRatio > 0.02) { score -= 0.15; signals.Add("style:human-todo-density"); }
        if (commentRatio < 0.05 && total > 40) { score -= 0.08; signals.Add("style:sparse-comments"); }
        return (Math.Clamp(score, 0.05, 0.95), signals);
    }

    private static string Preview(string[] lines, int startLine, int endLine)
    {
        var start = Math.Max(0, startLine - 1);
        var end = Math.Min(lines.Length, endLine);
        var take = Math.Min(end - start, 60);
        var chunk = string.Join('\n', lines.Skip(start).Take(take));
        if (end - start > take)
            chunk += "\n…";
        return chunk;
    }

    private static IReadOnlyList<string> SuggestOracleFocus(List<BugHunterBlockDto> blocks)
    {
        var focus = new List<string>();
        if (blocks.Any(b => b.Provenance is BugHunterProvenance.LikelyAi or BugHunterProvenance.AnnotatedAi))
        {
            focus.Add("auth");
            focus.Add("state");
            focus.Add("integer");
            focus.Add("structure");
            focus.Add("resource");
        }
        else
        {
            focus.Add("invariant");
            focus.Add("structure");
        }
        return focus;
    }

    private static IReadOnlyList<string> SuggestMistakes(List<BugHunterBlockDto> blocks)
    {
        var aiHeavy = blocks.Count(b => b.Provenance is BugHunterProvenance.LikelyAi or BugHunterProvenance.AnnotatedAi)
                      >= Math.Max(1, blocks.Count / 4);
        return aiHeavy
            ? BugHunterMistakes.All.Where(m => m.Id != "mem-classic").Select(m => m.Id).Take(8).ToList()
            : BugHunterMistakes.All.Select(m => m.Id).Take(5).ToList();
    }

    [GeneratedRegex(@"AI[-_ ]?GENERATED|@ai-generated|RANDALL:AI", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex AnnotationAiRegex();
    [GeneratedRegex(@"BEGIN\s+AI|AI\s+START", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex BeginAiRegex();
    [GeneratedRegex(@"END\s+AI|AI\s+END", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex EndAiRegex();
    [GeneratedRegex(@"HUMAN[-_ ]?WRITTEN|@human|RANDALL:HUMAN", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex AnnotationHumanRegex();
    [GeneratedRegex(@"BEGIN\s+HUMAN|HUMAN\s+START", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex BeginHumanRegex();
    [GeneratedRegex(@"END\s+HUMAN|HUMAN\s+END", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex EndHumanRegex();
    [GeneratedRegex(@"copilot|github\s*copilot", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex CopilotRegex();
    [GeneratedRegex(@"chatgpt|openai", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex ChatGptRegex();
    [GeneratedRegex(@"\bclaude\b|anthropic", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex ClaudeRegex();
    [GeneratedRegex(@"cursor\s*agent|generated by cursor", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex CursorAgentRegex();
    [GeneratedRegex(@"auto[- ]?generated|code(?:gen)?(?:erated)?\s+by", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex CodegenRegex();
    [GeneratedRegex(@"generated by", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex GeneratedByRegex();
}
