namespace Randall.Contracts;

public static class RandallRoadmap
{
    public static IReadOnlyList<RoadmapPhaseDto> Phases =>
    [
        new(1, "Lab targets + crash loop", "complete",
        [
            new("p1-yaml", "Project YAML loader", true, null),
            new("p1-mutators", "Tricky mutators", true, null),
            new("p1-vulnserver", "vulnserver TCP (TRUN)", true, null),
            new("p1-file-text", "File target — structured text/XML", true, null),
            new("p1-file-framed", "File target — length-prefixed binary", true, null),
            new("p1-crashes", "Crash store + index.jsonl", true, null),
            new("p1-cli", "CLI targets/fuzz/crashes", true, null),
            new("p1-replay", "Full replay", true, null),
            new("p1-minidump", "Minidump on hang", true, null),
            new("p1-web", "Web crash browser", true, null),
            new("p1-model", "Block protocol models (Leg 1)", true, "docs/MODEL.md"),
        ]),
        new(2, "Stalk (DynamoRIO)", "complete",
        [
            new("p2-drcov", "drcov wrapper", true, null),
            new("p2-corpus", "Corpus priority by edges", true, null),
            new("p2-web-fuzz", "Web UI fuzz control + SignalR", true, null),
            new("p2-gui", "Coverage on file targets", true, null),
        ]),
        new(3, "Network + proxy", "complete",
        [
            new("p3-session", "Vulnserver session graph", true, null),
            new("p3-mitm", "MITM proxy capture", true, null),
            new("p3-replay", "Live edit / replay in proxy", true, null),
        ]),
        new(4, "Crash stalking + Ghidra", "complete",
        [
            new("p4-dedup", "Path dedup + first diverge", true, null),
            new("p4-export", "Triage bundle export", true, null),
            new("p4-ghidra", "Ghidra / Dragon Dance artifacts", true, null),
        ]),
        new(5, "Plugins + autopilot", "complete",
        [
            new("p5-rpp", "RPP process plugins", true, null),
            new("p5-campaign", "Campaign scheduler", true, null),
            new("p5-pack", "Portable publish bundle", true, null),
            new("p5-bundle", "Project zip export", true, "randall bundle"),
        ]),
        new(6, "Intelligence + polish", "complete",
        [
            new("p6-field", "Field-aware model mutation", true, null),
            new("p6-size", "Size / length block primitive", true, "docs/MODEL.md"),
            new("p6-import", "bundle import command", true, "randall bundle import"),
            new("p6-dedup", "Crash hash dedup", true, null),
        ]),
        new(7, "Lab agent + mobility", "complete",
        [
            new("p7-agent", "randall agent — bind all interfaces", true, "randall agent"),
            new("p7-bundles-ui", "Web bundle export/import", true, null),
            new("p7-vuln-models", "Full vulnserver block models", true, null),
            new("p7-local", "Discover gitignored local projects", true, "projects/local/"),
            new("p7-autopilot", "Cursor Automations nightly template", true, "docs/AUTOPILOT.md"),
        ]),
        new(8, "Advanced techniques", "complete",
        [
            new("p8-havoc", "AFL-style stacked havoc mutator", true, "docs/FUZZING.md"),
            new("p8-interesting", "LibFuzzer interesting integers", true, null),
            new("p8-dictionary", "Dictionary / token injection", true, null),
            new("p8-splice", "Corpus crossover (splice)", true, null),
            new("p8-power", "Corpus energy power schedule", true, null),
            new("p8-flows", "Stateful TCP session flows", true, null),
            new("p8-clusters", "Crash clustering for triage", true, "/api/crashes/clusters"),
        ]),
        new(9, "Lab readiness", "complete",
        [
            new("p9-doctor", "randall doctor preflight checks", true, "randall doctor"),
            new("p9-udp", "UDP datagram transport", true, null),
            new("p9-crc", "CRC32 checksum block + resync", true, "docs/MODEL.md"),
            new("p9-havoc-model", "Field-level havoc in model fuzzer", true, null),
        ]),
        new(10, "Kidnap Boo (protocol parity)", "complete",
        [
            new("p10-primitives", "string/delim/word/dword/choices blocks", true, "docs/MODEL.md"),
            new("p10-exhaustive", "Exhaustive fuzz mode + mutateStep", true, "docs/BOOFUZZ_PARITY.md"),
            new("p10-processmon", "ProcessMonitor for long-lived targets", true, null),
            new("p10-vulnhttp", "VulnHttp lab server + project", true, "projects/vulnhttp.yaml"),
            new("p10-vulnftp", "VulnFtp lab server + FTP session flows", true, "projects/vulnftp.yaml"),
            new("p10-vulnssh", "VulnSsh stub server + project", true, "projects/vulnssh.yaml"),
            new("p10-examples", "examples/ gallery (http, ftp)", true, "docs/EXAMPLES.md"),
        ]),
        new(11, "Camouflage (TLS + responses)", "complete",
        [
            new("p11-tls", "TLS transport (SslStream)", true, "examples/https-simple"),
            new("p11-expect", "expectResponse session validation", true, null),
            new("p11-postrecv", "RPP post_receive hook + ftp-response plugin", true, "docs/RPP.md"),
            new("p11-tcpdump", "TCP server minidump on crash", true, null),
            new("p11-importer", "External script → YAML importer", true, "scripts/import-boofuzz.py"),
            new("p11-smoke", "lab-smoke campaign covers all lab targets", true, "campaigns/lab-smoke.yaml"),
        ]),
        new(12, "Stalk the factory (TCP + TFTP)", "complete",
        [
            new("p12-vulntftp", "VulnTftp UDP lab server + project", true, "projects/vulntftp.yaml"),
            new("p12-graph", "sessionGraph response branching (s_switch)", true, "docs/MODEL.md"),
            new("p12-postcrash", "RPP post_crash + crash-tag plugin", true, "docs/RPP.md"),
            new("p12-tcpcov", "TCP coverage via instrumented spawn (drcov)", true, null),
            new("p12-udpmon", "UDP long-lived process crash detection", true, null),
        ]),
        new(13, "Night shift (graph + triage)", "complete",
        [
            new("p13-graph-cli", "randall graph — validate + Mermaid export", true, null),
            new("p13-graph-api", "/api/graph + doctor sessionGraph check", true, null),
            new("p13-tags", "Crash triage tags in index + web UI", true, null),
            new("p13-ci", "CI lab-smoke campaign dry-run", true, ".github/workflows/ci.yml"),
            new("p13-tftp-ex", "examples/tftp-simple gallery entry", true, "examples/tftp-simple"),
        ]),
        new(14, "Graph editor (web UI)", "complete",
        [
            new("p14-graph-tab", "Session graph tab — Mermaid diagram + edge table", true, null),
            new("p14-yaml-snippet", "YAML snippet viewer + copy", true, null),
            new("p14-graph-meta", "Validation errors/warnings in UI", true, null),
            new("p14-practice", "Lab practice guide for hands-on testing", true, "docs/LAB_PRACTICE.md"),
        ]),
        new(15, "Deep logging (journal + crash sidecars)", "complete",
        [
            new("p15-journal", "iterations.jsonl + run.json execution journal", true, "docs/EXECUTION_LOGGING.md"),
            new("p15-sidecar", "crash.json sidecar with lineage + coverage at crash", true, "docs/CRASH_LOGGING.md"),
            new("p15-trace-copy", "Per-crash trace copy under crashes/traces/", true, null),
            new("p15-stalk-backend", "Backend-agnostic stalk IDs (external vs native)", true, null),
            new("p15-minidump", "Richer minidump flags + file-target crash dumps", true, null),
        ]),
        new(16, "Native stalk (Randall-owned)", "in progress",
        [
            new("p16-native", "Windows native PC stalk (debug events → drcov)", true, "coarse; prefer external for full BB"),
            new("p16-edge-freq", "Edge hit counters + hot-spot detection", true, "run.json hotEdges"),
            new("p16-analyze", "randall analyze — registers from dump", true, "docs/CRASH_ANALYSIS.md"),
            new("p16-stalk-backend", "IStalkTraceBackend pluggable adapter", true, "external | native | none"),
        ]),
        new(17, "Pentest stalker (Dynapstalker workflow)", "in progress",
        [
            new("p17-layers", "Baseline / fuzzed / fuzzier stalk layers + compare", true, "Stalking bugs tab"),
            new("p17-idc", "IDA IDC color export (layered)", true, "/api/stalk/export"),
            new("p17-ghidra", "Ghidra Python color export", true, "/api/stalk/export"),
            new("p17-ui", "Stalking bugs workspace — graph layers in Randfuzz", true, null),
            new("p17-tools", "Tool probe: DynamoRIO, ProcDump, Procmon, WinDbg", true, "status badges"),
            new("p17-windbg", "WinDbg + Preview attach / open dump", true, "debuggerMode + /api/debug"),
            new("p17-scream", "Scream watcher — first-party exception dump", true, "replaces ProcDump wait"),
            new("p17-scream-selftest", "scream selftest + screamcrash lab target", true, "ACCESS_VIOLATION harness"),
            new("p17-procdump", "ProcDump optional fallback", true, "not required"),
            new("p17-procmon", "Procmon capture bookends (fuzz.procmonCapture)", true, "ProcmonCapture"),
            new("p17-tcpvcon", "TCPVCon network snapshots (fuzz.tcpvconCapture)", true, "TcpvconCapture"),
            new("p17-procdump-arm", "ProcDump -e -ma arm (fuzz.procdumpOnCrash)", true, "ProcDumpCrashArm"),
            new("p17-pktmon", "pktmon ETL bookends (fuzz.pktmonCapture)", true, "PktmonCapture"),
            new("p17-tshark", "tshark pcapng bookends (fuzz.tsharkCapture)", true, "TsharkCapture"),
            new("p17-etw", "WPR/ETW bookends (fuzz.etwCapture)", true, "EtwCapture"),
            new("p17-debugview", "DebugView OutputDebugString capture (fuzz.debugViewCapture)", true, "DebugViewCapture"),
            new("p17-sysinternals-snap", "Sysinternals snapshots bundle (fuzz.sysinternalsSnapshots)", true, "SysinternalsSnapshots"),
            new("p17-sigcheck", "SigCheck on target exe at arm (in snapshots)", true, "sigcheck-target.txt"),
            new("p17-accesschk", "AccessChk process token in snapshots", true, "accesschk64 -p -f"),
            new("p17-strings-crash", "Strings on crashing input (fuzz.stringsOnCrash)", true, "StringsOnCrash"),
            new("p17-vmmap-cli", "VMMap best-effort CLI in snapshots (GUI companion primary)", true, "vmmap64 -p"),
            new("p17-remote", "Remote stalk agent APIs on randall agent", true, "/api/remote/procmon|/tools"),
            new("p17-regs", "Registers from analyze / crash UI (live WinDbg panel later)", true, "analyze + crash detail"),
            new("p17-case", "Case builder — seeds, dicts, new/edit YAML targets", true, "docs/CASE_BUILDER.md"),
            new("p17-custom", "Custom target docs + templates (name: → Target profile)", true, "docs/CUSTOM_TARGETS.md"),
        ]),
        new(18, "Scare Floor Network (app-layer packets)", "in progress",
        [
            new("p18-steps", "Network recipe = ordered session steps (multi-PDU)", true, "CaseSessionStepDto"),
            new("p18-ui", "Scare Floor UI: add/reorder steps + mutate-which-step", true, "sessionFlows"),
            new("p18-preview", "Per-step ASCII/hex preview + byte editor", true, "/api/case/preview-session"),
            new("p18-apply", "Apply session → YAML sessionCommands/Flows", true, "/api/case/apply-session"),
            new("p18-ftp-flow", "FTP login flow multi-PDU preset", true, null),
            new("p18-proxy", "Import Proxy capture → network recipe", true, "Send to Scare Floor"),
            new("p18-presets", "More network presets (SMTP, Redis, custom binary)", true, "SMTP + Redis flows"),
            new("p18-stream", "Import TCP stream / app payload → steps", true, "Import as session + from-stream"),
            new("p18-docs", "Docs: fuzz remote TCP from Scare Floor", true, "docs/CASE_BUILDER.md"),
        ]),
        new(19, "Wire Scare Floor ↔ sessions/models", "in progress",
        [
            new("p19-flows", "Save recipe → sessionFlows / sessionCommands", true, "Apply to Campaign (Phase 18)"),
            new("p19-graph-edit", "Edit sessionGraph edges in web UI", true, "POST /api/graph"),
            new("p19-expect", "expectResponse per step in Scare Floor", true, "PDU expect field"),
            new("p19-promote", "Promote steps → projects/protocols model YAML", true, "docs/MODEL.md"),
            new("p19-dict", "Dictionary harvest across session steps", true, "Apply + Save dict"),
            new("p19-cli", "randall case from-stream / apply-session", true, null),
        ]),
        new(20, "Protocol packs", "done",
        [
            new("p20-format", "Pack format: recipe + protocol YAML + example project", true, "projects/protocols/packs/"),
            new("p20-http", "HTTP/1.1 request pack (headers as fields)", true, "packs/http-get"),
            new("p20-ftp", "FTP login → STOR/RETR flow pack", true, "packs/ftp-login"),
            new("p20-tlv", "Generic TLV / length-prefixed pack", true, "packs/tlv-frame"),
            new("p20-dns", "DNS/mDNS UDP query pack (lab)", true, "packs/dns-query"),
            new("p20-boofuzz", "Boofuzz example → Scare Floor recipe", true, "scripts/import-boofuzz.py --recipe"),
            new("p20-wizard", "Custom protocol wizard (magic + len + body + CRC)", true, "Scare Floor wizard"),
        ]),
        new(21, "RPC / DCE-RPC (lab-first)", "done",
        [
            new("p21-bind", "DCE/RPC bind + request framing model", true, "dce_bind / dce_request"),
            new("p21-ndr", "NDR stub as hex + sized fields (manual layout)", true, "stub bytes + opnum"),
            new("p21-session", "Session: bind → request* via sessionFlows", true, "packs/dce-bind-request"),
            new("p21-lab", "Tiny crashable RPC stub lab server", true, "VulnRpc :1355"),
            new("p21-docs", "Docs: fuzz RPC with known stub layout", true, "docs/RPC_LAB.md"),
            new("p21-idl", "Optional simple IDL → field map (stretch)", true, "randall case idl"),
        ]),
        new(22, "SMB (session-aware, lab-first)", "done",
        [
            new("p22-nbss", "NetBIOS session service framing", true, "NBSS on smb2_* PDUs"),
            new("p22-nego", "SMB2 Negotiate + Session Setup (null/guest lab)", true, "no Kerberos v1"),
            new("p22-tree", "Tree Connect + Create + Read/Write models", true, "smb2_create / write / read"),
            new("p22-graph", "sessionGraph on SMB status codes", true, "vulnsmb.yaml"),
            new("p22-lab", "Lab VM guidance for vulnerable SMB", true, "VulnSmb :4455 + SMB_LAB.md"),
            new("p22-pipe", "Named pipe → DCERPC reuse (Phase 21)", true, "packs/smb-pipe-dce"),
        ]),
        new(23, "Layered PDU builder (Scapy workflow, Randall-owned)", "done",
        [
            new("p23-layers", "Layered PDU builder in Scare Floor", true, "Layers panel"),
            new("p23-fields", "Field table edit (type, endian, fuzzable)", true, "field table toggle"),
            new("p23-templates", "Stack templates from protocol packs", true, "NBSS/SMB2/DCE + TLV"),
            new("p23-json", "Recipe JSON interchange (CLI + UI + scripts)", true, "layers on sessionSteps"),
            new("p23-fixups", "Autocalc length/checksum across layers", true, "nbss / u24be-rest + crc32"),
            new("p23-policy", "No Scapy dependency — optional import only", true, "in-house primary"),
        ]),
        new(24, "Packet forge (in-house L2–L4)", "planned",
        [
            new("p24-layers", "Ether/VLAN/IP/IPv6/TCP/UDP/ICMP field models", false, null),
            new("p24-rebuild", "Build → mutate → rebuild (len/checksum fixups)", false, null),
            new("p24-send", "Raw socket / pcap inject (Win + Linux adapters)", false, "privilege-aware"),
            new("p24-dissect", "Capture → dissect → Scare Floor layers", false, null),
            new("p24-modes", "Campaign: TCP stream mode vs packet mode", false, null),
            new("p24-safety", "Lab-only defaults; no internet-scan presets", false, null),
            new("p24-interop", "Optional Scapy/hex/pcap import — never required", false, null),
        ]),
    ];
}
