namespace Randall.Contracts;

public static class RandallRoadmap
{
    public static IReadOnlyList<RoadmapPhaseDto> Phases =>
    [
        new(1, "Lab targets + crash loop", "complete",
        [
            new("p1-yaml", "Project YAML loader", true, null),
            new("p1-mutators", "Tricky mutators", true, null),
            new("p1-vulnserver", "vulnserver TCP (TRUN)", true, null),
            new("p1-file-text", "File target — structured text/XML", true, null),
            new("p1-file-framed", "File target — length-prefixed binary", true, null),
            new("p1-crashes", "Crash store + index.jsonl", true, null),
            new("p1-cli", "CLI targets/fuzz/crashes", true, null),
            new("p1-replay", "Full replay", true, null),
            new("p1-minidump", "Minidump on hang", true, null),
            new("p1-web", "Web crash browser", true, null),
            new("p1-model", "Block protocol models (Leg 1)", true, "docs/MODEL.md"),
        ]),
        new(2, "Stalk (DynamoRIO)", "complete",
        [
            new("p2-drcov", "drcov wrapper", true, null),
            new("p2-corpus", "Corpus priority by edges", true, null),
            new("p2-web-fuzz", "Web UI fuzz control + SignalR", true, null),
            new("p2-gui", "Coverage on file targets", true, null),
        ]),
        new(3, "Network + proxy", "complete",
        [
            new("p3-session", "Vulnserver session graph", true, null),
            new("p3-mitm", "MITM proxy capture", true, null),
            new("p3-replay", "Live edit / replay in proxy", true, null),
        ]),
        new(4, "Crash stalking + Ghidra", "complete",
        [
            new("p4-dedup", "Path dedup + first diverge", true, null),
            new("p4-export", "Triage bundle export", true, null),
            new("p4-ghidra", "Ghidra / Dragon Dance artifacts", true, null),
        ]),
        new(5, "Plugins + autopilot", "complete",
        [
            new("p5-rpp", "RPP process plugins", true, null),
            new("p5-campaign", "Campaign scheduler", true, null),
            new("p5-pack", "Portable publish bundle", true, null),
            new("p5-bundle", "Project zip export", true, "randall bundle"),
        ]),
        new(6, "Intelligence + polish", "complete",
        [
            new("p6-field", "Field-aware model mutation", true, null),
            new("p6-size", "Size / length block primitive", true, "docs/MODEL.md"),
            new("p6-import", "bundle import command", true, "randall bundle import"),
            new("p6-dedup", "Crash hash dedup", true, null),
        ]),
        new(7, "Lab agent + mobility", "complete",
        [
            new("p7-agent", "randall agent — bind all interfaces", true, "randall agent"),
            new("p7-bundles-ui", "Web bundle export/import", true, null),
            new("p7-vuln-models", "Full vulnserver block models", true, null),
            new("p7-local", "Discover gitignored local projects", true, "projects/local/"),
            new("p7-autopilot", "Cursor Automations nightly template", true, "docs/AUTOPILOT.md"),
        ]),
        new(8, "Advanced techniques", "complete",
        [
            new("p8-havoc", "AFL-style stacked havoc mutator", true, "docs/FUZZING.md"),
            new("p8-interesting", "LibFuzzer interesting integers", true, null),
            new("p8-dictionary", "Dictionary / token injection", true, null),
            new("p8-splice", "Corpus crossover (splice)", true, null),
            new("p8-power", "Corpus energy power schedule", true, null),
            new("p8-flows", "Stateful TCP session flows", true, null),
            new("p8-clusters", "Crash clustering for triage", true, "/api/crashes/clusters"),
        ]),
        new(9, "Lab readiness", "complete",
        [
            new("p9-doctor", "randall doctor preflight checks", true, "randall doctor"),
            new("p9-udp", "UDP datagram transport", true, null),
            new("p9-crc", "CRC32 checksum block + resync", true, "docs/MODEL.md"),
            new("p9-havoc-model", "Field-level havoc in model fuzzer", true, null),
        ]),
        new(10, "Kidnap Boo (protocol parity)", "complete",
        [
            new("p10-primitives", "string/delim/word/dword/choices blocks", true, "docs/MODEL.md"),
            new("p10-exhaustive", "Exhaustive fuzz mode + mutateStep", true, "docs/BOOFUZZ_PARITY.md"),
            new("p10-processmon", "ProcessMonitor for long-lived targets", true, null),
            new("p10-vulnhttp", "VulnHttp lab server + project", true, "projects/vulnhttp.yaml"),
            new("p10-vulnftp", "VulnFtp lab server + FTP session flows", true, "projects/vulnftp.yaml"),
            new("p10-vulnssh", "VulnSsh stub server + project", true, "projects/vulnssh.yaml"),
            new("p10-examples", "examples/ gallery (http, ftp)", true, "docs/EXAMPLES.md"),
        ]),
        new(11, "Camouflage (TLS + responses)", "complete",
        [
            new("p11-tls", "TLS transport (SslStream)", true, "examples/https-simple"),
            new("p11-expect", "expectResponse session validation", true, null),
            new("p11-postrecv", "RPP post_receive hook + ftp-response plugin", true, "docs/RPP.md"),
            new("p11-tcpdump", "TCP server minidump on crash", true, null),
            new("p11-importer", "External script → YAML importer", true, "scripts/import-boofuzz.py"),
            new("p11-smoke", "lab-smoke campaign covers all lab targets", true, "campaigns/lab-smoke.yaml"),
        ]),
        new(12, "Stalk the factory (TCP + TFTP)", "complete",
        [
            new("p12-vulntftp", "VulnTftp UDP lab server + project", true, "projects/vulntftp.yaml"),
            new("p12-graph", "sessionGraph response branching (s_switch)", true, "docs/MODEL.md"),
            new("p12-postcrash", "RPP post_crash + crash-tag plugin", true, "docs/RPP.md"),
            new("p12-tcpcov", "TCP coverage via instrumented spawn (drcov)", true, null),
            new("p12-udpmon", "UDP long-lived process crash detection", true, null),
        ]),
        new(13, "Night shift (graph + triage)", "complete",
        [
            new("p13-graph-cli", "randall graph — validate + Mermaid export", true, null),
            new("p13-graph-api", "/api/graph + doctor sessionGraph check", true, null),
            new("p13-tags", "Crash triage tags in index + web UI", true, null),
            new("p13-ci", "CI lab-smoke campaign dry-run", true, ".github/workflows/ci.yml"),
            new("p13-tftp-ex", "examples/tftp-simple gallery entry", true, "examples/tftp-simple"),
        ]),
        new(14, "Graph editor (web UI)", "complete",
        [
            new("p14-graph-tab", "Session graph tab — Mermaid diagram + edge table", true, null),
            new("p14-yaml-snippet", "YAML snippet viewer + copy", true, null),
            new("p14-graph-meta", "Validation errors/warnings in UI", true, null),
            new("p14-practice", "Lab practice guide for hands-on testing", true, "docs/LAB_PRACTICE.md"),
        ]),
        new(15, "Deep logging (journal + crash sidecars)", "complete",
        [
            new("p15-journal", "iterations.jsonl + run.json execution journal", true, "docs/EXECUTION_LOGGING.md"),
            new("p15-sidecar", "crash.json sidecar with lineage + coverage at crash", true, "docs/CRASH_LOGGING.md"),
            new("p15-trace-copy", "Per-crash trace copy under crashes/traces/", true, null),
            new("p15-stalk-backend", "Backend-agnostic stalk IDs (external vs native)", true, null),
            new("p15-minidump", "Richer minidump flags + file-target crash dumps", true, null),
        ]),
        new(16, "Native stalk (Randall-owned)", "in progress",
        [
            new("p16-native", "Windows native PC stalk (debug events → drcov)", true, "coarse; prefer external for full BB"),
            new("p16-edge-freq", "Edge hit counters + hot-spot detection", true, "run.json hotEdges"),
            new("p16-analyze", "randall analyze — registers from dump", true, "docs/CRASH_ANALYSIS.md"),
            new("p16-stalk-backend", "IStalkTraceBackend pluggable adapter", true, "external | native | none"),
        ]),
        new(17, "Pentest stalker (Dynapstalker workflow)", "in progress",
        [
            new("p17-layers", "Baseline / fuzzed / fuzzier stalk layers + compare", true, "Stalking bugs tab"),
            new("p17-idc", "IDA IDC color export (layered)", true, "/api/stalk/export"),
            new("p17-ghidra", "Ghidra Python color export", true, "/api/stalk/export"),
            new("p17-ui", "Stalking bugs workspace — graph layers in Randfuzz", true, null),
            new("p17-tools", "Tool probe: DynamoRIO, ProcDump, Procmon, WinDbg", true, "status badges"),
            new("p17-windbg", "WinDbg + Preview attach / open dump", true, "debuggerMode + /api/debug"),
            new("p17-scream", "Scream watcher — first-party exception dump", true, "replaces ProcDump wait"),
            new("p17-scream-selftest", "scream selftest + screamcrash lab target", true, "ACCESS_VIOLATION harness"),
            new("p17-procdump", "ProcDump optional fallback", true, "not required"),
            new("p17-procmon", "Procmon capture bookends (fuzz.procmonCapture)", true, "ProcmonCapture"),
            new("p17-remote", "Remote stalk agent APIs on randall agent", true, "/api/remote/procmon|/tools"),
            new("p17-regs", "Registers from analyze / crash UI (live WinDbg panel later)", true, "analyze + crash detail"),
            new("p17-case", "Case builder — seeds, dicts, new/edit YAML targets", true, "docs/CASE_BUILDER.md"),
            new("p17-custom", "Custom target docs + templates (name: → Target profile)", true, "docs/CUSTOM_TARGETS.md"),
        ]),
    ];
}
